SELECT CASE
           WHEN GRADES.GRADE < 8 THEN NULL
           ELSE STUDENTS.NAME
       END AS NAME,
       GRADES.GRADE,
       STUDENTS.MARKS
FROM STUDENTS
INNER JOIN GRADES ON STUDENTS.MARKS BETWEEN GRADES.MIN_MARK AND GRADES.MAX_MARK
ORDER BY GRADES.GRADE DESC, NAME ASC, MARKS ASC;